[package]
name = "opengl_chrno"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytemuck = "1.22.0"
gl33 = "0.2.1"
beryllium = "0.13.3"

[dev-dependencies]
imagine = "0.5.1"